replicaCount: 2

image:
  repository: yangchun3728/yc
  pullPolicy: Always
  tag: "4610b7731d87726882b21f3cfc12179d0b85e85e"

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

ingress:
  enabled: true
  className: nginx
  hosts:
    - host: springboot.local
      paths:
        - path: /
          pathType: Prefix

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi