replicaCount: 5

image:
  repository: yangchun3728/yc
  pullPolicy: Always
  tag: "2f5c07ad20a0c898c786edec273a6074670cdeb0"

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

ingress:
  enabled: true
  className: nginx
  hosts:
    - host: springboot.local
      paths:
        - path: /
          pathType: Prefix

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi